#!/usr/bin/env ruby
# starts chrome process

# xvfd command line guide
# start xvfd with screen backed by a file
# Xvfd :1 -screen 0 1280x1024x24 -fbdir /tmp
# take a peek at the screen:

# xwud -in /tmp/Xvfb_screen0 
require 'bundler/setup'
require 'backports'

require_relative '../config/settings'
require_relative '../lib/sveg/utils'

def usage
	$stdout.puts "usage: #{__FILE__} start|stop|restart|cmd_line"; exit
end

def start
	puts "starting chromium"
	pid = Kernel.spawn(SvegSettings.chrome_binary,
										 "--user-data-dir=#{SvegSettings.chrome_profile_dir}",
										 "--no-sandbox",
										 :chdir => SvegSettings.chrome_profile_dir,
										 :out => File.join(SvegSettings.log_dir, "chromepdf_error.log"),
										 :err => File.join(SvegSettings.log_dir, "chromepdf_error.log"))
	 Process.detach(pid)
	 pid
end

def stop
	pid  = PB::CommandLine.get_chromium_pid
	if pid then
		Process.kill("TERM", pid)
		puts "stopping chromium"
	end
end

usage unless ARGV.length == 1 && ARGV[0].match(/start|stop|restart|cmd_line/)
case 
	when ARGV[0].eql?("start") then start
	when ARGV[0].eql?("stop") then stop
	when ARGV[0].eql?("restart") then stop;start
	when ARGV[0].eql?('cmd_line') then
		line =  "#{SvegSettings.chrome_binary} --user-data-dir=#{SvegSettings.chrome_profile_dir}"
		line += " --no-sandbox "
		puts line
		STDERR.write "remember to redirect output to 2> #{File.join(SvegSettings.log_dir, "chromepdf_error.log")}"
	else usage
end
