#!/usr/bin/env ruby
# starts chrome process
# TODO daemonize script/chrome with xvfd, taskless gem for Linux

require 'config/settings'
require 'svegutils'

def usage
  $stdout.puts "usage: #{__FILE__} start|stop"; exit
end

def start
  puts "starting chromium"
  PB::CommandLine.launch_chrome
end

def stop
  pid  = PB::CommandLine.get_chromium_pid
  (Process.kill("TERM", pid);puts "stopping chromium") if pid
end

usage unless ARGV.length == 1
case 
  when ARGV[0].eql?("start") then start
  when ARGV[0].eql?("stop") then stop
  else "usage"
end

# OBSOLETE CODE
# 
# myARGV = [ARGV, [
#     "--", 
#     "--user-data-dir=#{SvegSettings.chrome_profile_dir}",
#     "--no-sandbox" 
#     ]].flatten
# 
# 
# Daemons.run(SvegSettings.chrome_binary, {
#   :app_name => "chromepdf",
#   :ARGV => myARGV,
#   :dir_mode => :normal,
#   :dir => SvegSettings.tmp_dir,
#   :backtrace => true,
#   :monitor => false,
#   :log_dir => SvegSettings.log_dir,
#   :log_output => true,
# })