#!/usr/bin/env ruby

require 'config/settings'
require 'delayed/command'
require 'app/book2pdf_job'

# process ids in tmp
ARGV.push("--pid-dir=#{SvegSettings.tmp_dir}") unless ARGV.index { |item| (item.start_with? "--pid-dir")  }
# process name. Use  ps -A | grep sveg_delayed_job
Delayed::Command.new(ARGV).daemonize
