#!/usr/bin/env ruby
# starts main sveg server

require 'bundler/setup'
require 'backports'
require_relative '../config/settings'

options = {
	:port => 26000,
	:rackup => File.expand_path(File.join(File.dirname(__FILE__), "../sveg.rb")),
	:log => File.join(SvegSettings.log_dir, 'sveg_error.log'),
	:pid => File.join(SvegSettings.tmp_dir, 'sveg.pid'),
	:tag => "sveg_#{SvegSettings.environment.to_s[0..3]}",
}

require_relative './common'

process(options)

#out = `#{cmd_line_args} 2>&1`
#puts out unless out.empty?
#puts "Error in sveg" unless $?.success?
